name: Agrinho_Frecheirinha
description: Ações do Programa Agrinho Escola Francisco Ferreira Pontes.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  convex_bottom_bar: ^3.2.0
  assets_audio_player: ^3.0.8
  photo_view: ^0.14.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/inicial/
    - assets/alimentacao/
    - assets/boca/
    - assets/obesidade/
    - assets/saudavel/
    - assets/icons/
    - assets/songs/
    - assets/frecheirinha/
    - assets/escola/





flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21



flutter_native_splash:
  image: assets/icons/splash.png
  color: "#FFFFFF"
  fill: true

